FROM alpine:latest
MAINTAINER Bjorn Kjeholt <dev@kjeholt.se>

RUN mkdir /scripts
WORKDIR /app
VOLUME /app
COPY Scripts/ /scripts/

RUN apk add --update mysql mysql-client vim && \
    rm -f /var/cache/apk/*
COPY my.cnf /etc/mysql/my.cnf

EXPOSE 3306
HEALTHCHECK CMD ["/scripts/docker-healthcheck"]
CMD ["/scripts/startup.sh"]
