# ************************************************************************
# Product    : Home information and control
# Date       : 2017-02-23
# Copyright  : Copyright (C) 2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : mysql/docker-compose-rpi.yml
# Version    : 1.2.0
# Author     : Bjorn Kjeholt
# *************************************************************************

version: '2.1'

services:
  mysql:
    image: hypriot/rpi-mysql:latest
    ports:
      - "${MYSQL_PORT_NO}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db

  phpmyadmin:
    image: bkjeholt/phpmyadmin:latest-rpi
    depends_on:
      - mysql
    restart: always
    links: 
      - mysql:db
    ports: 
      - "${PMA_PORT_NO}:80"

volumes:
  mysql_data: 
