FROM alpine:latest
MAINTAINER Bjorn Kjeholt <dev@kjeholt.se>

RUN mkdir /scripts
WORKDIR /var/lib/mysql
VOLUME /var/lib/mysql
COPY Scripts/ /scripts/

RUN apk add --update mysql mysql-client bash vim && \
    rm -f /var/cache/apk/* && \
    chmod 755 /scripts/*

COPY dbConfigs/my.cnf /etc/mysql/my.cnf

ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}

EXPOSE 3306
HEALTHCHECK CMD ["/scripts/docker-healthcheck"]
CMD ["/scripts/startup.sh"]
